//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PhotoFinder
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbModelContainer object using the connection string found in the 'dbModelContainer' section of the application configuration file.
        /// </summary>
        public dbModelContainer() : base("name=dbModelContainer", "dbModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbModelContainer object.
        /// </summary>
        public dbModelContainer(string connectionString) : base(connectionString, "dbModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbModelContainer object.
        /// </summary>
        public dbModelContainer(EntityConnection connection) : base(connection, "dbModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pictures> Pictures
        {
            get
            {
                if ((_Pictures == null))
                {
                    _Pictures = base.CreateObjectSet<Pictures>("Pictures");
                }
                return _Pictures;
            }
        }
        private ObjectSet<Pictures> _Pictures;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pictures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPictures(Pictures pictures)
        {
            base.AddObject("Pictures", pictures);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="Pictures")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pictures : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pictures object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="sCD">Initial value of the SCD property.</param>
        public static Pictures CreatePictures(global::System.Int32 id, global::System.String name, global::System.String path, global::System.String url, SCD sCD)
        {
            Pictures pictures = new Pictures();
            pictures.Id = id;
            pictures.Name = name;
            pictures.Path = path;
            pictures.Url = url;
            pictures.SCD = StructuralObject.VerifyComplexObjectIsNotNull(sCD, "SCD");
            return pictures;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion
        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public SCD SCD
        {
            get
            {
                _SCD = GetValidValue(_SCD, "SCD", false, _SCDInitialized);
                _SCDInitialized = true;
                return _SCD;
            }
            set
            {
                OnSCDChanging(value);
                ReportPropertyChanging("SCD");
                _SCD = SetValidValue(_SCD, value, "SCD");
                _SCDInitialized = true;
                ReportPropertyChanged("SCD");
                OnSCDChanged();
            }
        }
        private SCD _SCD;
        private bool _SCDInitialized;
        partial void OnSCDChanging(SCD value);
        partial void OnSCDChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="dbModel", Name="SCD")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class SCD : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SCD object.
        /// </summary>
        /// <param name="property">Initial value of the Property property.</param>
        public static SCD CreateSCD(global::System.Byte[] property)
        {
            SCD sCD = new SCD();
            sCD.Property = property;
            return sCD;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Property
        {
            get
            {
                return StructuralObject.GetValidValue(_Property);
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.Byte[] _Property;
        partial void OnPropertyChanging(global::System.Byte[] value);
        partial void OnPropertyChanged();

        #endregion
    }

    #endregion
    
}
