//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PhotosModel", "Tags", "Photo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PhotoFinder.Photo), "Tag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PhotoFinder.Tag))]

#endregion

namespace PhotoFinder
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PhotosEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PhotosEntities object using the connection string found in the 'PhotosEntities' section of the application configuration file.
        /// </summary>
        public PhotosEntities() : base("name=PhotosEntities", "PhotosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PhotosEntities object.
        /// </summary>
        public PhotosEntities(string connectionString) : base(connectionString, "PhotosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PhotosEntities object.
        /// </summary>
        public PhotosEntities(EntityConnection connection) : base(connection, "PhotosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Photo> PhotoSet
        {
            get
            {
                if ((_PhotoSet == null))
                {
                    _PhotoSet = base.CreateObjectSet<Photo>("PhotoSet");
                }
                return _PhotoSet;
            }
        }
        private ObjectSet<Photo> _PhotoSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tag> TagSet
        {
            get
            {
                if ((_TagSet == null))
                {
                    _TagSet = base.CreateObjectSet<Tag>("TagSet");
                }
                return _TagSet;
            }
        }
        private ObjectSet<Tag> _TagSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PhotoSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPhotoSet(Photo photo)
        {
            base.AddObject("PhotoSet", photo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TagSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTagSet(Tag tag)
        {
            base.AddObject("TagSet", tag);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PhotosModel", Name="Photo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Photo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Photo object.
        /// </summary>
        /// <param name="photoID">Initial value of the PhotoID property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="sCD">Initial value of the SCD property.</param>
        /// <param name="cLD">Initial value of the CLD property.</param>
        /// <param name="eHD">Initial value of the EHD property.</param>
        /// <param name="cEDD">Initial value of the CEDD property.</param>
        /// <param name="fCTH">Initial value of the FCTH property.</param>
        public static Photo CreatePhoto(global::System.String photoID, global::System.String title, global::System.Byte[] sCD, global::System.Byte[] cLD, global::System.Byte[] eHD, global::System.Byte[] cEDD, global::System.Byte[] fCTH)
        {
            Photo photo = new Photo();
            photo.PhotoID = photoID;
            photo.Title = title;
            photo.SCD = sCD;
            photo.CLD = cLD;
            photo.EHD = eHD;
            photo.CEDD = cEDD;
            photo.FCTH = fCTH;
            return photo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PhotoID
        {
            get
            {
                return _PhotoID;
            }
            set
            {
                if (_PhotoID != value)
                {
                    OnPhotoIDChanging(value);
                    ReportPropertyChanging("PhotoID");
                    _PhotoID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PhotoID");
                    OnPhotoIDChanged();
                }
            }
        }
        private global::System.String _PhotoID;
        partial void OnPhotoIDChanging(global::System.String value);
        partial void OnPhotoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] SCD
        {
            get
            {
                return StructuralObject.GetValidValue(_SCD);
            }
            set
            {
                OnSCDChanging(value);
                ReportPropertyChanging("SCD");
                _SCD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SCD");
                OnSCDChanged();
            }
        }
        private global::System.Byte[] _SCD;
        partial void OnSCDChanging(global::System.Byte[] value);
        partial void OnSCDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] CLD
        {
            get
            {
                return StructuralObject.GetValidValue(_CLD);
            }
            set
            {
                OnCLDChanging(value);
                ReportPropertyChanging("CLD");
                _CLD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CLD");
                OnCLDChanged();
            }
        }
        private global::System.Byte[] _CLD;
        partial void OnCLDChanging(global::System.Byte[] value);
        partial void OnCLDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] DCD
        {
            get
            {
                return StructuralObject.GetValidValue(_DCD);
            }
            set
            {
                OnDCDChanging(value);
                ReportPropertyChanging("DCD");
                _DCD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DCD");
                OnDCDChanged();
            }
        }
        private global::System.Byte[] _DCD;
        partial void OnDCDChanging(global::System.Byte[] value);
        partial void OnDCDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] EHD
        {
            get
            {
                return StructuralObject.GetValidValue(_EHD);
            }
            set
            {
                OnEHDChanging(value);
                ReportPropertyChanging("EHD");
                _EHD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EHD");
                OnEHDChanged();
            }
        }
        private global::System.Byte[] _EHD;
        partial void OnEHDChanging(global::System.Byte[] value);
        partial void OnEHDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] CEDD
        {
            get
            {
                return StructuralObject.GetValidValue(_CEDD);
            }
            set
            {
                OnCEDDChanging(value);
                ReportPropertyChanging("CEDD");
                _CEDD = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CEDD");
                OnCEDDChanged();
            }
        }
        private global::System.Byte[] _CEDD;
        partial void OnCEDDChanging(global::System.Byte[] value);
        partial void OnCEDDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] FCTH
        {
            get
            {
                return StructuralObject.GetValidValue(_FCTH);
            }
            set
            {
                OnFCTHChanging(value);
                ReportPropertyChanging("FCTH");
                _FCTH = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FCTH");
                OnFCTHChanged();
            }
        }
        private global::System.Byte[] _FCTH;
        partial void OnFCTHChanging(global::System.Byte[] value);
        partial void OnFCTHChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PhotosModel", "Tags", "Tag")]
        public EntityCollection<Tag> Tags
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tag>("PhotosModel.Tags", "Tag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tag>("PhotosModel.Tags", "Tag", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PhotosModel", Name="Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Tag CreateTag(global::System.Int32 id, global::System.String name)
        {
            Tag tag = new Tag();
            tag.Id = id;
            tag.Name = name;
            return tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PhotosModel", "Tags", "Photo")]
        public EntityCollection<Photo> Photos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Photo>("PhotosModel.Tags", "Photo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Photo>("PhotosModel.Tags", "Photo", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
